name: Desktop builder
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build Desktop
    runs-on: ubuntu-latest
    env:
      QT_VERSION: 6.11.0
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: apt installs
        run: |
          sudo apt-get update
          sudo apt-get install python3 pip build-essential libgl1-mesa-dev \
          libxkbcommon-x11-0 cmake unzip default-jdk default-jdk
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'linux'
          target: 'desktop'
      - name: Build Desktop
        run: |
          cd viMarkdown
          CMAKE_PREFIX_PATH=/qt/${QT_VERSION}/gcc_64 cmake -B build_linux_x86
          cmake --build build_linux_x86
      
          